### ISSUE TITLE
Possible performance issue on GenericMesh structure

### ISSUE THREAD

**Issue by maltezfaria** [WaveProp/DensityInterpolationMethod#1]
@Riarrieta This type of mesh structure may lead to performance issue down the road. Maybe use a function barrier here?

https://github.com/WaveProp/DensityInterpolationMethod/blob/22179b6b7ceb489cd719a586bb01d5f0a8b2d278/src/Mesh/meshes.jl#L12

**Comment by Riarrieta** [comment]
I changed the mesh structure. Elements are now stored in a dictionary with pairs `(d=>v)`, where `d` is an element `DataType` (e.g. `FlatTriangleElement`) and `v` is a `Vector` of elements of type `d`. This should facilitate the use of function barriers.

https://github.com/WaveProp/DensityInterpolationMethod/blob/1cbbc97b2f492d92f0e73a73123f819df9cf61bd/src/Mesh/meshes.jl#L11-L17

**Comment by maltezfaria** [comment]
Thanks!
