### ISSUE TITLE
Doubt with double layer kernel

### ISSUE THREAD

**Issue by Riarrieta** [WaveProp/DensityInterpolationMethod#2]
Hi @maltezfaria. I was cheking the Maxwell's single and double layer kernels in WaveProp and I found a discrepancy with respect to the double layer kernel that I implemented in Fortran. In WaveProp (code below), line 39 (without the minus sign) agrees with my kernel implementation and line 40 does not. I'm almost sure that line 39 (without the minus sign) is the one that we should be using (`n \times (eq. 7)` in Carlos' notes), nevertheless, do you mind double-checking this?

https://github.com/WaveProp/WaveProp/blob/1fc2d2c4b9526d8ec17e6e26a42201594c815dee/src/Nystrom/maxwell.jl#L19-L42

**Comment by maltezfaria** [comment]
* I think lines `39` and `40` that you mentioned are the same. It is just "anti-commuting" the cross product ( and thus the minus sign).
* The sign difference with your own formula on the other hand is probably just a convention. As long as we are consistent later on, it should be fine.

**Comment by Riarrieta** [comment]
Thanks @maltezfaria. I actually think that lines `39` and `40` are not the same (I'm getting different results too!). Consider `n` and `r` vector fields and `p` a surface vector density. In general we have that `n x (r x p)` is not equal to `-r x (n x p)`, therefore the matrices `ncross` and `rcross` in lines `39` and `40` do not anti-commute. You can also check this by doing the algebra.

**Comment by maltezfaria** [comment]
@Riarrieta you are correct: these are not the same. Let me check the notes and get back to you.

**Comment by maltezfaria** [comment]
Sorted out (I think). What you want is the commented out version of `WaveProp` (i.e. line `39`). Note, however, that the normals there were taken at the source location `y` (yet another mistake?), and on your notes they should be taken at the target location `x`. 

I never got `Maxwell` to work on `WaveProp`, but if we manage to get a working version here we should consider a merge.
